<?php 

if (class_exists('view_frontend_layouts_basic') == false ){ class view_frontend_layouts_basic{ 

public function M($V){ 
extract($V);
$_ ='';
$_ .= '<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>';
$_ .= $this->title($V);
$_ .= '</title>

    <link href="/assets/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="/assets/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="/assets/libs/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="/assets/app/css/frontend.css" rel="stylesheet" />
  </head>
  <body>
    <header>
	    <nav class="navbar navbar-inverse navbar-fixed-top">
	      <div class="container">
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	          <a class="navbar-brand" href="/">Wudimei MVC</a>
	        </div>
	        <div id="navbar" class="collapse navbar-collapse">
	          <ul class="nav navbar-nav">
	            <li class="active"><a href="/">Home</a></li>
	            <li><a href="#about">About</a></li>
	            <li><a href="#contact">Contact</a></li>
	          </ul>
	          <ul class="nav navbar-nav navbar-right">
	            ';
 if( isset( $_SESSION['user'] ) ){  
$_ .= '
	            <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><!-- ';
 $_ .=  htmlspecialchars( $user->username ); 
$_ .= ' --> <span class="caret"></span></a>
		          <ul class="dropdown-menu" role="menu">
		            <li><a href="/user/changePassword">';
 $_ .= trans('global.changePassword');
$_ .= '</a></li>
		            <li class="divider"></li>
		            <li><a href="/logout">';
 $_ .= trans('global.logout');
$_ .= '</a></li>
		          </ul>
		        </li>
	             ';
 }else{  
$_ .= '<li><a href="/login">';
 $_ .= trans('global.login');
$_ .= '</a></li>
	            <li><a href="/register">';
 $_ .= trans('global.register');
$_ .= '</a></li>
	            ';
 } 
$_ .= '</ul>
	        </div><!--/.nav-collapse -->
	      </div>
	    </nav>
    </header>
    
    
    
	  ';
$_ .= $this->content($V);
$_ .= '<div class="container"> 
    	<hr>

      <footer>
        <p>&copy; 2016  Company, Inc.</p>
      </footer>
    </div> <!-- /container -->
    
    <script src="/assets/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="/assets/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>';
return $_;
} 


public function title($V){ 
extract($V);
$_ ='';
 $_ .=  '' ;
return $_;
} 


public function content($V){ 
extract($V);
$_ ='';
$_ .= ' 
		wudimei.com
	  ';
return $_;
} 


} }  ?><?php 

if (class_exists('view_frontend_index') == false ){ class view_frontend_index extends view_frontend_layouts_basic{ 

public function M($V){ 
  return parent::M($V);
} 


public function content($V){ 
extract($V);
$_ ='';
$_ .= '
	<div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>
    
    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      
    </div> <!-- /container -->
    
';
return $_;
} 


} }  ?>