<!-- @{ 
	$user = \Auth::user(); 
} --><!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@section('title','Wudimei MVC')</title>
  	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <link href="/assets/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/libs/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" >
  
  	<link href="/assets/libs/AdminLTE/2.3.6/css/AdminLTE.min.css" rel="stylesheet" >
 	
 	 <link href="/assets/libs/AdminLTE/2.3.6/css/skins/skin-yellow.min.css" rel="stylesheet" >
 	 
    <!--[if lt IE 9]>
      <script src="/assets/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="/assets/libs/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
  </head>
  <body  class="hold-transition skin-yellow sidebar-mini">
     
   
  <div class="wrapper">

  <header class="main-header">
    <a href="../../index2.html" class="logo">
      <span class="logo-mini"><b>A</b>LT</span>
      <span class="logo-lg"><b>Admin</b>LTE</span>
    </a>
    <nav class="navbar navbar-static-top">
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="/assets/libs/AdminLTE/2.3.6/img/user2-160x160.jpg" class="user-image" alt="User Image">
              <span class="hidden-xs">{{@$user->username}}</span>
            </a>
            <ul class="dropdown-menu">
              <li class="user-header">
                <img src="/assets/libs/AdminLTE/2.3.6/img/user2-160x160.jpg" class="img-circle" alt="User Image">

                <p>
                  {{@$user->username}}
                  <!-- <small>Member since Nov. 2012</small> -->
                </p>
              </li><!--
              <li class="user-body">
              
                <div class="row">
                  <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                  </div>
                </div>
              </li> -->
              <li class="user-footer">
              <!--
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div> -->
                <div class="pull-right">
                  <a href="/logout" class="btn btn-default btn-flat">@trans('global.logout')</a>
                </div>
              </li>
            </ul>
          </li>
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-info"></i></a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <aside class="main-sidebar">
    <section class="sidebar">
      <div class="user-panel">
        <div class="pull-left image">
          <img src="/assets/libs/AdminLTE/2.3.6/img/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{@$user->username}}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> @trans('global.Online')</a>
        </div>
      </div>
      <!-- 
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
       -->
      <ul class="sidebar-menu">
        <li class="header">@trans('backend.MAIN_NAVIGATION')</li>
          
         @{ $bkMenu = new \App\Backend\Library\BackendMenu();     }  {! $bkMenu->getHtmlMenus()  !}
      </ul>
    </section>
  </aside>

  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        <!-- @section('content_header','Content Header') -->
        <small><!-- @section('content_header_desc','Content Header desc') --></small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{Config::get('app.backend_url')}}"><i class="fa fa-dashboard"></i> @trans('global.home')</a></li>
        <!-- @section('breadcrumb') -->
        <li><a href="#">Tables</a></li>
        <li class="active">Data tables</li>
        <!-- @endsection -->
      </ol>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          	 <!-- @section('content') -->
			wudimei.com
			<!-- @endsection -->
        </div>
      </div>
    </section>
  </div>
  
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.3.6
    </div>
    <strong>@trans('global.copyright') &copy; 2016-@date('Y') <a href="http://wudimei.com" target="_blank">Wudimei</a>.</strong> @trans('global.all_rights_reserved')
  </footer>
 
</div>

    <script src="/assets/libs/jquery/2.2.3/jquery.min.js"></script>
    <script src="/assets/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="/assets/libs/AdminLTE/2.3.6/js/app.js"></script>

  </body>
</html>