<!-- @{ 
	$user = \Auth::user(); 
} --><!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>@section('title','Wudimei MVC')</title>

    <link href="/assets/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="/assets/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="/assets/libs/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="/assets/app/css/frontend.css" rel="stylesheet" />
  </head>
  <body>
    <header>
	    <nav class="navbar navbar-inverse navbar-fixed-top">
	      <div class="container">
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	          <a class="navbar-brand" href="/">Wudimei MVC</a>
	        </div>
	        <div id="navbar" class="collapse navbar-collapse">
	          <ul class="nav navbar-nav">
	            <li class="active"><a href="/">Home</a></li>
	            <li><a href="#about">About</a></li>
	            <li><a href="#contact">Contact</a></li>
	          </ul>
	          <ul class="nav navbar-nav navbar-right">
	            <!-- @if( \Auth::check() ) -->
	            <li><a> <!-- {{$user->username}} --></a></li>
	            <li><a href="/logout">Logout</a></li>
	            <!-- @else -->
	            <li><a href="/login">Login</a></li>
	            <li><a href="/register">Register</a></li>
	            <!-- @endif -->
	          </ul>
	        </div><!--/.nav-collapse -->
	      </div>
	    </nav>
    </header>
    
    
    
	<!-- @section('content') -->
		wudimei.com
	<!-- @endsection -->
	
   	<div class="container"> 
    	<hr>

      <footer>
        <p>&copy; 2016  Company, Inc.</p>
      </footer>
    </div> <!-- /container -->
    
    <script src="/assets/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="/assets/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>