<!-- @extends('frontend.layouts.basic') -->

<!-- @section('content') -->

<div class="container">
	<div class="row">
		<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
			<h3>@trans('user.please_enter_the_new_password')</h3>
			<div>{{$message}}</div>
			<form class="form-horizontal" action="" method="post">
			  <div class="form-group @if(isset($validator_errors['new_password']))has-error@endif">
			    <label for="inputEmail3" class="col-sm-2 control-label">@trans('user.new_password')</label>
			    <div class="col-sm-10">
			      <input type="password" name="new_password" class="form-control" id="inputEmail3" placeholder="@trans('user.new_password')">
			      <p class="help-block">{{@$validator_errors['new_password']}}</p>
			    </div>
			  </div>
			  
			  <div class="form-group @if(isset($validator_errors['new_password2']))has-error@endif">
			    <label for="inputEmail3" class="col-sm-2 control-label">@trans('user.new_password')</label>
			    <div class="col-sm-10">
			      <input type="password" name="new_password2" class="form-control" id="inputEmail3" placeholder="@trans('user.new_password')">
			      <p class="help-block">{{@$validator_errors['new_password2']}}</p>
			    </div>
			  </div>
			  
			  <div class="form-group">
			    <div class="col-sm-offset-2 col-sm-10">
			      <button type="submit" class="btn btn-success">@trans('user.reset_password')</button>
			      <input type="hidden"  name="token"  value="{{$token}}" />
			    </div>
			  </div>
			</form>
			
		</div>
		
		<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
		
		</div>
		
	</div>
</div>

<!-- @endsection -->