<!-- @extends('frontend.layouts.basic') -->

<!-- @section('content') -->

<div class="container">
	<div class="row">
		<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
			<h3>Login</h3>
			
			<form class="form-horizontal" action="" method="post">
			  <div class="form-group">
			    <label for="inputEmail3" class="col-sm-2 control-label">Login</label>
			    <div class="col-sm-10">
			      <input type="text" name="login" class="form-control" id="inputEmail3" placeholder="Email or Username">
			    </div>
			  </div>
			  <div class="form-group">
			    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
			    <div class="col-sm-10">
			      <input type="password" name="password" class="form-control" id="inputPassword3" placeholder="Password">
			    </div>
			  </div>
			  <div class="form-group">
			    <div class="col-sm-offset-2 col-sm-10">
			      <div class="checkbox">
			        <label>
			          <input type="checkbox" name="remember_me"> Remember me 7 days
			        </label>
			      </div>
			    </div>
			  </div>
			  <div class="form-group">
			    <div class="col-sm-offset-2 col-sm-10">
			      <button type="submit" class="btn btn-default">Sign in</button>
			    </div>
			  </div>
			</form>
			
		</div>
		
		<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
		
		</div>
		
	</div>
</div>

<!-- @endsection -->