<?php return array (
  'SITE.NAME' => '深圳市无敌美电子商务商行2',
  'SITE.ADDRESS' => '广东省深圳市d',
  'SITE.ZIPCODE' => '518100',
  'SEO.KEYWORDS' => '关键字1,关键字',
  'SITE.CELLPHONE' => '13714715608',
  'SITE.FAX' => '075500000000',
  'SITE.CONTACTMAN' => '杨庆荣',
  'SEO.DESCRIPTION' => '描述，220个字符以内。22',
  'SITE.URL_PREFIX' => 'http://wudimeishop.anli.wudimei.com',
  'LINKS.IMAGE_SIZE' => '80,404',
  'SITE.QQ' => '290359552,杨庆荣
214341,张',
  'MAIL.TYPE' => 'mail',
  'MAIL.SMTP_SSL' => 'yes',
  'MAIL.SMTP_HOST' => 'smtp.gmail.com',
  'MAIL.SMTP_PORT' => '465',
  'MAIL.SMTP_USERNAME' => 'fsdaf',
  'MAIL.SMTP_PASSWORD' => 'f',
  'MAIL.SMTP_FROM' => '',
  'MAIL.SMTP_DEBUG' => 'no',
  'GUESTBOOK.REJECT_BAD_WORDS' => 'yes',
  'GUESTBOOK.ENABLE_EMAIL_NOTIFICATION' => 'yes',
  'FILTER.BAD_WORDS' => '法轮功,法轮大法,色情,赌博,六合彩',
  'GUESTBOOK.RECEIVER_EMAIL' => 'yaqy@qq.com',
  'ORDER.ENABLE_NOTIFYING_ADMIN' => 'no',
  'ORDER.EMAILS_FOR_NOTIFICATION' => 'yaqy@qq.com,290359552@qq.com',
  'admin.email' => '****@wudimei.com',
  'hobbies3' => 'drink',
  'hobbies' => 'eat,drink,ridding',
  'hobbies4' => 'eat,drink',
); ?>