<!-- @extends('backend.layouts.master') -->

<!-- @section('title') -->
	<!-- @if($method == 'edit' ) --> <!-- @trans('user.editUser')--> <!-- @else --> <!-- @trans('user.addUser')--> <!-- @endif -->
<!-- @endsection -->
 
<!-- @section('content_header' ) --> 
	<!-- @if($method == 'edit' ) --> <!-- @trans('user.editUser')--> <!-- @else --> <!-- @trans('user.addUser')--> <!-- @endif -->
<!-- @endsection -->

<!-- @section('content_header_desc' ) --> 
	<!-- @if($method == 'edit' ) --> <!-- @trans('user.editUser_desc')--> <!-- @else --> <!-- @trans('user.addUser_desc')--> <!-- @endif -->
<!-- @endsection -->

<!-- @section('breadcrumb') -->
        <li class="active">
        <!-- @if($method == 'edit' ) --> <!-- @trans('user.editUser')--> <!-- @else --> <!-- @trans('user.addUser')--> <!-- @endif -->
        </li>
<!-- @endsection -->
        
<!-- @section('content') --> 
 
  
	<div class="box">
		 
        <div class="box-body">
        
        	 
        	 
        </div>
       
	</div>
   
	 
	 

<!-- @endsection -->
